name: vimbisopay_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  http: ^1.1.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.1.6
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.20
  url_launcher: ^6.1.12
  sqflite: ^2.3.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  screen_brightness: ^0.2.2
  audioplayers: ^5.2.1
  firebase_messaging: ^14.7.4
  firebase_core: ^2.22.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - assets/animations/
    - assets/audio/
