name: vimbisopay_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.5
  http: ^1.2.2
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.25
  sqflite: ^2.3.2
  path: ^1.8.3
  encrypt: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
