// File generated by setup-firebase-config.sh
// Do not edit by hand

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Add other platforms if needed in the future
    throw UnsupportedError(
      'DefaultFirebaseOptions are not configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveZsYwNeHjEMEav0859ojYhQTh6j3nQE',
    appId: '1:39107041024:web:b17d22c7fd995abc18c5e5',
    messagingSenderId: '39107041024',
    projectId: 'vimbisopay',
    authDomain: 'vimbisopay.firebaseapp.com',
    storageBucket: 'vimbisopay.firebasestorage.app',
    measurementId: 'G-V613FEEENC',
  );
}
