#!/bin/sh

# Run Flutter tests
echo "Running tests before push..."
flutter test

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "❌ Tests must pass before pushing!"
 exit 1
fi

echo "✅ Tests passed!"
exit 0
